# Generated by Django 2.2.5 on 2019-10-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191002_1334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(max_length=4128)),
                ('payment', models.CharField(choices=[('finished', 'Finished work'), ('hour', 'Per Hour'), ('day', 'Per Day'), ('month', 'Per Month'), ('year', 'Per Year')], default='finished', max_length=120)),
                ('money', models.FloatField(verbose_name='Деньги за работу')),
                ('currency', models.CharField(choices=[('dollar', '$'), ('sum', 'sum'), ('euro', '€')], default='dollar', max_length=120)),
                ('date_finished', models.DateField(verbose_name='Дата окончания работы')),
                ('type_of_work', models.CharField(choices=[('fixed', 'Fixed Work')], default='fixed', max_length=120)),
                ('duration', models.CharField(max_length=120)),
                ('job_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_given', to='accounts.CompanyModel')),
                ('job_taken', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_taken', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, to='jobs.SkillsModel')),
            ],
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.JobsModel'),
        ),
        migrations.AlterField(
            model_name='proposalmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobs.JobsModel'),
        ),
        migrations.DeleteModel(
            name='JobsFLModel',
        ),
    ]
