# Generated by Django 2.2.5 on 2019-09-26 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsflmodel',
            name='job_taken',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='JobDoneby', to=settings.AUTH_USER_MODEL),
        ),
    ]
