# Generated by Django 2.2.5 on 2019-09-26 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobsflmodel_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsflmodel',
            name='currency',
            field=models.CharField(choices=[('dollar', '$'), ('sum', 'sum'), ('euro', '€')], default='dollar', max_length=120),
        ),
        migrations.AlterField(
            model_name='jobsflmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
