# Generated by Django 2.2.5 on 2019-09-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190926_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalmodel',
            name='skills',
        ),
    ]
