# Generated by Django 2.2.5 on 2019-10-02 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('banner', models.ImageField(upload_to='company/banner/')),
                ('bannerMini', models.ImageField(default='', upload_to='company/banner/mini/')),
                ('logo', models.ImageField(upload_to='company/logo/')),
                ('about', models.TextField(max_length=1024)),
                ('employees', models.CharField(choices=[('small', '2-9 Employees'), ('medium', '10-99 Employees'), ('big', '100-499 Employees'), ('very big', 'More than 500 Employees')], default='medium', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('social_twitter', models.CharField(default=None, max_length=240)),
                ('social_facebook', models.CharField(default=None, max_length=240)),
                ('social_linkedin', models.CharField(default=None, max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
