# Generated by Django 2.2.5 on 2019-09-22 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('banner', models.ImageField(height_field=300, upload_to='company/banner/', width_field=1100)),
                ('logo', models.ImageField(height_field=100, upload_to='company/logo/', width_field=100)),
                ('about', models.CharField(max_length=240)),
                ('verified', models.BooleanField(default=False)),
                ('social_twitter', models.CharField(default=None, max_length=240)),
                ('social_facebook', models.CharField(default=None, max_length=240)),
                ('social_linkedin', models.CharField(default=None, max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
