# Generated by Django 2.2.5 on 2019-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='bannerMini',
            field=models.ImageField(default='', upload_to='company/banner/mini/'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='banner',
            field=models.ImageField(upload_to='company/banner/'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='logo',
            field=models.ImageField(upload_to='company/logo/'),
        ),
    ]
