# Generated by Django 2.2.5 on 2019-09-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190923_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='employees',
            field=models.CharField(choices=[('small', '1-9 Employees'), ('medium', '10-99 Employees'), ('big', '100-499 Employees'), ('very big', 'More than 500 Employees')], default='medium', max_length=20),
        ),
    ]
