# Generated by Django 2.2.5 on 2019-09-26 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companymodel_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
